import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GlobalStyle from "@/shared/styled/GlobalStyled";
import ClientLayout from "./ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "coffeeOrder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalStyle />
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
