import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/shared/client/styled/common/common.css';
import '@/shared/admin/styled/admin_common.css';
import ClientLayout from "./ClientLayout";
import viewport from "./viewport";
import Script from "next/script";
import { dehydrate, HydrationBoundary, QueryClient } from "@tanstack/react-query";
import { productGetApi } from "@/features/adminApi/adminProductApi";
import QueryProvider from "./globalProvider/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "coffeeOrder",
  manifest: '/manifest.json',
  description: "Generated by create next app",
  appleWebApp: {capable: true, statusBarStyle: "black-translucent", title: "coffeeOrder"},
  icons: { icon: '/icons/icon-192.png', apple: '/icons/icon-192.png' },
};

export {viewport};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const queryClient = new QueryClient();

  const allProduct = await productGetApi(); //전체 제품 조회

  await Promise.all([
    queryClient.prefetchQuery({ queryKey: ['products'], queryFn: allProduct }),
  ]);

  return (
    <html 
      lang="ko"
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Script
          src="https://pay.nicepay.co.kr/v1/js/"
          strategy="beforeInteractive"
        />
        <QueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <ClientLayout>
              {children}
            </ClientLayout>
          </HydrationBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
